---
# Source: ingressmonitorcontroller/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: ingressmonitorcontroller
  annotations:
  labels:
    app: ingressmonitorcontroller
    chart: "ingressmonitorcontroller-1.0.49"
    release: "RELEASE-NAME"
    heritage: "Tiller"
    version: 1.0.49
    
    group: com.stakater.platform
    provider: stakater
    
data:
  config.yaml: |-
    providers:
    - name: UptimeRobot
      apiKey: your-api-key
      apiURL: https://google.com
      username: null
      password: null
      alertContacts: some-alert-contacts
    enableMonitorDeletion: true
    monitorNameTemplate: "{{.Namespace}}-{{.IngressName}}"
