---
# Source: ingressmonitorcontroller/templates/deployment.yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    configmap.reloader.stakater.com/reload: ingressmonitorcontroller
    
  labels:
    app: ingressmonitorcontroller
    chart: "ingressmonitorcontroller-1.0.48"
    release: "RELEASE-NAME"
    heritage: "Tiller"
    version: 1.0.48
    
    group: com.stakater.platform
    provider: stakater
    
  name: ingressmonitorcontroller
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: ingressmonitorcontroller
      release: "RELEASE-NAME"
      group: com.stakater.platform
      provider: stakater
      
  template:
    metadata:
      labels:
        app: ingressmonitorcontroller
        chart: "ingressmonitorcontroller-1.0.48"
        release: "RELEASE-NAME"
        heritage: "Tiller"
        version: 1.0.48
        
        group: com.stakater.platform
        provider: stakater
        
    spec:
      containers:
      - env:
        - name: CONFIG_FILE_PATH
          value: /etc/IngressMonitorController/config.yaml
        image: "stakater/ingressmonitorcontroller:1.0.48"
        imagePullPolicy: IfNotPresent
        name: ingressmonitorcontroller
        volumeMounts:
        - mountPath: /etc/IngressMonitorController
          name: config-volume
      serviceAccountName: ingressmonitorcontroller
      volumes:
      - configMap:
          name: ingressmonitorcontroller
        name: config-volume
