---
# Source: ingressmonitorcontroller/templates/rbac.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: ingressmonitorcontroller
    version: 1.0.38
    group: com.stakater.platform
    provider: stakater
    chart: "ingressmonitorcontroller-1.0.38"
    release: "RELEASE-NAME"
    heritage: "Tiller"
  name: ingressmonitorcontroller
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: ingressmonitorcontroller-role
rules:
  - apiGroups:
      - ""
      - "extensions"
    resources:
      - ingresses
    verbs:
      - list
      - get
      - update
      - patch
      - watch
      - delete
  - apiGroups:
      - ""
    resources:
      - services
      - pods
    verbs:
      - list
      - get
      - watch
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: ingressmonitorcontroller-role-binding
roleRef:
  kind: ClusterRole
  name: ingressmonitorcontroller-role
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: ingressmonitorcontroller
  namespace: default
