---
# Source: ingressmonitorcontroller/templates/serviceaccount.yaml

apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: ingressmonitorcontroller
    chart: "ingressmonitorcontroller-SNAPSHOT-release-v1-2"
    release: "ingressmonitorcontroller"
    heritage: "Tiller"
    version: SNAPSHOT-release-v1-2
    
    group: com.stakater.platform
    provider: stakater
    
  name: ingressmonitorcontroller
