---
# Source: ingressmonitorcontroller/templates/serviceaccount.yaml

apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: ingressmonitorcontroller
    chart: "ingressmonitorcontroller-1.0.48"
    release: "RELEASE-NAME"
    heritage: "Tiller"
    version: 1.0.48
    
    group: com.stakater.platform
    provider: stakater
    
  name: ingressmonitorcontroller
