global:
# labels added on all components of chart in addition to some default labels
  labels: {}

# can have comma separated namespace names
# if empty, IMC will look in all namespaces, 
watchNamespaces: ""
useFullName: false
deployment:
  labels: {}
  annotations:
    configmap.reloader.stakater.com/reload: ingressmonitorcontroller
  replicas: 1
  revisionHistoryLimit: 2
  operatorName: ingressmonitorcontroller
  logLevel: info
  logFormat: text
  
  image:
    name: "stakater/ingressmonitorcontroller"
    tag: v2.0.15
    pullPolicy: Always
rbac:
  create: true
  serviceAccount:
    create: true
    name: ""
    labels: {}
    annotations: {}

secret:
  useExisting: false 
  name: ""
  labels: {}
  annotations: {}
  data:
    config.yaml: |-
      providers:
      - name: UptimeRobot
        apiKey: your-api-key
        apiURL: https://google.com
        alertContacts: some-alert-contacts
      enableMonitorDeletion: true
      monitorNameTemplate: "{{.Namespace}}-{{.IngressName}}"
      # how often (in seconds) monitors should be synced to their Kubernetes resources (0 = disabled)
      resyncPeriod: 0
      # creationDelay is a duration string to add a delay before creating new monitor (e.g., to allow DNS to catch up first)
      # https://golang.org/pkg/time/#ParseDuration
      creationDelay: 0