providers: 
  - name: UptimeRobot
    apiKey: u673984-fd42aadaa63288101e169864
    apiURL: https://api.uptimerobot.com/v2/
    alertContacts: "0673984_0_0"
  - name: Pingdom
    apiKey: SYrCQG7MN6PmdD9VkFTRgqwW5vO2En
    apiURL: https://api.pingdom.com/api/2.1
    username: stakatertest
enableMonitorDeletion: true
