apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- crds/endpointmonitor.stakater.com_endpointmonitors_crd.yaml
- operator.yaml
- role.yaml
- role_binding.yaml
- service_account.yaml
