apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingressmonitorcontroller
spec:
  replicas: 1
  selector:
    matchLabels:
      name: ingressmonitorcontroller
  template:
    metadata:
      labels:
        name: ingressmonitorcontroller
    spec:
      serviceAccountName: ingressmonitorcontroller
      containers:
        - name: ingressmonitorcontroller
          # Replace this with the built image name
          image: REPLACE_IMAGE
          command:
          - ingressmonitorcontroller
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "ingressmonitorcontroller"
              # TODO: Remove this and use a secret
            - name: CONFIG_FILE_PATH
              value: /etc/IngressMonitorController/config.yaml
            - name: LOG_LEVEL
              value: info
            - name: LOG_FORMAT
              value: text

