apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: ingressmonitorcontroller
rules:
- apiGroups:
  - ""
  - "extensions"
  - "route.openshift.io"
  resources:
  - ingresses
  - routes
  - secrets
  verbs:
  - list
  - get
- apiGroups:
  - ""
  resources:
  - events
  - services
  - configmaps
  - services/finalizers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  - replicasets
  - statefulsets
  verbs:
  - "*"
- apiGroups:
  - monitoring.coreos.com
  resources:
  - servicemonitors
  verbs:
  - get
  - create
  - list
- apiGroups:
  - apps
  resourceNames:
  - ingressmonitorcontroller
  resources:
  - deployments/finalizers
  verbs:
  - update
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
- apiGroups:
  - endpointmonitor.stakater.com
  resources:
  - '*'
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
