---
# Source: ingressmonitorcontroller/templates/role.yaml

---
# Source: ingressmonitorcontroller/templates/deployment.yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    configmap.reloader.stakater.com/reload: ingressmonitorcontroller
    
  labels:
    app: ingressmonitorcontroller
    chart: "ingressmonitorcontroller-v1.0.85"
    release: "RELEASE-NAME"
    heritage: "Tiller"
    version: v1.0.85
    
    group: com.stakater.platform
    provider: stakater
    
  name: ingressmonitorcontroller
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: ingressmonitorcontroller
      release: "RELEASE-NAME"
      group: com.stakater.platform
      provider: stakater
      
  template:
    metadata:
      labels:
        app: ingressmonitorcontroller
        chart: "ingressmonitorcontroller-v1.0.85"
        release: "RELEASE-NAME"
        heritage: "Tiller"
        version: v1.0.85
        
        group: com.stakater.platform
        provider: stakater
        
    spec:
      containers:
      - env:
        - name: CONFIG_FILE_PATH
          value: /etc/IngressMonitorController/config.yaml
        - name: LOG_LEVEL
          value: info
        - name: LOG_FORMAT
          value: text
        image: "stakater/ingressmonitorcontroller:v1.0.85"
        imagePullPolicy: IfNotPresent
        name: ingressmonitorcontroller
        volumeMounts:
        - mountPath: /etc/IngressMonitorController
          name: ingressmonitorcontroller-vol
      serviceAccountName: ingressmonitorcontroller
      volumes:
        - name: ingressmonitorcontroller-vol
          configMap:
            name: ingressmonitorcontroller
---
# Source: ingressmonitorcontroller/templates/clusterrole.yaml

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: ingressmonitorcontroller-role
rules:
  - apiGroups:
      - ""
      - "extensions"
      - "route.openshift.io"
    resources:
      - ingresses
      - routes
    verbs:
      - list
      - get
      - update
      - patch
      - watch
      - delete
  - apiGroups:
      - ""
    resources:
      - services
      - pods
    verbs:
      - list
      - get
      - watch
---
# Source: ingressmonitorcontroller/templates/rolebinding.yaml

---
# Source: ingressmonitorcontroller/templates/secrets.yaml


---
# Source: ingressmonitorcontroller/templates/clusterrolebinding.yaml

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: ingressmonitorcontroller-role-binding
roleRef:
  kind: ClusterRole
  name: ingressmonitorcontroller-role
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: ingressmonitorcontroller
  namespace: default
---
# Source: ingressmonitorcontroller/templates/configmap.yaml

apiVersion: v1
kind: ConfigMap
metadata:
  name: ingressmonitorcontroller
  annotations:
  labels:
    app: ingressmonitorcontroller
    chart: "ingressmonitorcontroller-v1.0.85"
    release: "RELEASE-NAME"
    heritage: "Tiller"
    version: v1.0.85
    
    group: com.stakater.platform
    provider: stakater
    
data:
  config.yaml: "providers:\n- name: UptimeRobot\n  apiKey: your-api-key\n  apiURL: https://google.com\n
    \ alertContacts: some-alert-contacts\nsecrets: {}\n# - variable: environment-variable-name\t\n#
    \  name: secret-name\n#   key: secret-key\nenableMonitorDeletion: true\nmonitorNameTemplate:
    \"{{.Namespace}}-{{.IngressName}}\"\n# how often (in seconds) monitors should be
    synced to their Kubernetes resources (0 = disabled)\nresyncPeriod: 0\n# creationDelay
    is a duration string to add a delay before creating new monitor (e.g., to allow
    DNS to catch up first)\n# https://golang.org/pkg/time/#ParseDuration\ncreationDelay:
    0"
  

---
# Source: ingressmonitorcontroller/templates/serviceaccount.yaml

apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: ingressmonitorcontroller
    chart: "ingressmonitorcontroller-v1.0.85"
    release: "RELEASE-NAME"
    heritage: "Tiller"
    version: v1.0.85
    
    group: com.stakater.platform
    provider: stakater
    
  name: ingressmonitorcontroller
