{{- if not .Values.secret.useExisting }}
apiVersion: v1
kind: Secret
metadata:
{{- if .Values.secret.name }}
  name: {{ .Values.secret.name | quote }}
{{- else }}
  name: {{ template "name" . }}
{{- end }}
  annotations:
{{- if .Values.secret.annotations }}
{{ toYaml .Values.secret.annotations | indent 4 }}
{{- end }}
  labels:
{{ include "labels" $ | indent 4 }}
{{- if .Values.secret.labels }}
{{ toYaml .Values.secret.labels | indent 4 }}
{{- end }}
data:
{{- range $key, $value := .Values.secret.data }}
  {{ $key }}: {{ $value | b64enc }}
{{- end }}
{{- end }}