{{- if .Values.serviceAccount.create -}}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ingress-monitor-controller.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ingress-monitor-controller.labels" . | nindent 4 }}
    {{- if .Values.rbac.serviceAccount.labels }}
    {{ toYaml .Values.rbac.serviceAccount.labels | indent 4 }}
    {{- end }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
