{{- if and ( .Values.rbac.create ) (.Values.rbac.serviceAccount.create) }}
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
{{- if .Values.rbac.serviceAccount.annotations }}
{{ toYaml .Values.rbac.serviceAccount.annotations | indent 4 }}
{{- end }}
  labels:
{{ include "labels" $ | indent 4 }}
{{- if .Values.rbac.serviceAccount.labels }}
{{ toYaml .Values.rbac.serviceAccount.labels | indent 4 }}
{{- end }}
  name: {{ template "serviceAccountName" . }}
{{- end }}