{{- if and ( .Values.rbac.create ) ( ne .Values.watchNamespaces "") }}
{{- range .Values.watchNamespaces | split "," }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ template "name" $ }}-role
  namespace: {{ . | quote }}
  labels:
{{ include "labels" $ | indent 4 }}
rules:
- apiGroups:
  - ""
  - "extensions"
  - "route.openshift.io"
  resources:
  - ingresses
  - routes
  - secrets
  verbs:
  - list
  - get
  - watch
- apiGroups:
  - ""
  resources:
  - events
  - services
  - configmaps
  - services/finalizers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  - replicasets
  - statefulsets
  verbs:
  - "list"
  - "get"
- apiGroups:
  - monitoring.coreos.com
  resources:
  - servicemonitors
  verbs:
  - get
  - create
  - list
- apiGroups:
  - apps
  resourceNames:
  - ingressmonitorcontroller
  resources:
  - deployments/finalizers
  verbs:
  - update
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - endpointmonitor.stakater.com
  resources:
  - '*'
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
---
{{- end }}
{{- end }}